# HIT137 - Group 84
# Name : Ricky Maharjan - ID-s359074
# Name : Abinab D C - ID-s360320
# Questions 1 - 10 Marks Create a program using turtle

import turtle
import random
from turtle import*
t=Turtle()
screen = turtle.Screen()
background_color = "#38285c"
screen.bgcolor(background_color)
screen.setup(width = 1.0, height = 1.0) #Set full screen window
 
#function to draw circle with size and color
def draw_circle(size,color):
    t.pendown()
    t.color(color)
    t.fillcolor(color)
    t.begin_fill()
    t.circle(size)
    t.end_fill()
    t.penup()

#function to draw triangle with size and color    
def draw_triangle(size,color):
    t.pendown()
    t.setheading(0)
    t.color(color)
    t.fillcolor(color)
    t.begin_fill()
    for i in range(3):
        t.fd(size)
        t.lt(120)
    t.end_fill()
    t.penup()

    
######### Cristmas tree starts here ########
# Creating Right half of the tree
t.begin_fill()
t.fillcolor("green")
t.forward(200)
t.left(150)
t.forward(180)
t.right(150)
t.forward(110)
t.left(150)
t.forward(140)
t.right(150)
t.forward(80)
t.left(150)
t.forward(130)
t.end_fill()

#left half of the tree
t.begin_fill()
t.fillcolor("green")
t.left(60)
t.forward(130)
t.left(150)
t.forward(80)
t.right(150)
t.forward(140)
t.left(150)
t.forward(110)
t.right(150)
t.forward(180)
t.left(150)
t.forward(200)
t.end_fill()

#Creating the trunck of the tree
t.penup()
t.color("brown")
t.goto(20,0)
t.begin_fill()
t.right(90)
t.forward(80)
t.right(90)
t.forward(40)
t.right(90)
t.forward(80)
t.end_fill()

#Creating the balls on the Christmas Tree
t.goto(120,-10)
draw_circle(10,"red")
t.goto(210,-10)
draw_circle(10,"blue")
t.goto(-100,-10)
draw_circle(10,"red")
t.goto(-185,-10)
draw_circle(10,"blue")
t.goto(160,80)
draw_circle(10,"yellow")
t.goto(-145,80)
draw_circle(10,"yellow")
t.goto(120,150)
draw_circle(10,"red")
t.goto(-100,150)
draw_circle(10,"red")
t.goto(5,25)
draw_circle(7,"yellow")
t.goto(5,90)
draw_circle(7,"red")
t.goto(5,160)
draw_circle(7,"blue")

#Drawing the bells using triangle.
t.goto(-80,30)
draw_triangle(15,"yellow")
t.goto(70,30)
draw_triangle(15,"red")
t.goto(-50,110)
draw_triangle(15,"blue")
t.goto(30,110)
draw_triangle(15,"yellow")

# Drawing the star using for loop
t.penup()
t.color("yellow")
t.goto(-20,240)
t.begin_fill()
t.pendown()
for i in range(5):
    t.forward(40)
    t.right(144)
t.end_fill()
######## Cristmas tree end here ########
 
#####Draw hallowen Pumpkin start#####
#Draw first circle
t.penup()
t.goto(-500,-300)
draw_circle(150,"orange")
#Draw second circle
t.goto(-580,-300)
draw_circle(150,"orange")
#Draw Traingles inside pumpkin
t.goto(-650,-100)
draw_triangle(50,"red")
t.goto(-480,-100)
draw_triangle(50,"red")
t.goto(-560,-170)
draw_triangle(40,"red")
t.goto(-625,-240)
for i in range(8):
    draw_triangle(25,"red")
    t.fd(20)
#Draw steam of pumpkin
t.goto(-570,-20)
draw_triangle(50,"green")
t.goto(-555,0)
t.color("green")
t.fillcolor("green")
t.begin_fill()
t.fd(20)
t.lt(90)
t.fd(40)
t.lt(90)
t.fd(20)
t.lt(90)
t.fd(40)
t.end_fill()
####Draw hallowen Pumpkin end##### 
 
##### Draw Flag start ####
t.penup()
t.goto(350,0)
t.setheading(0)
t.color("#003594")
t.fillcolor("#003594")
t.begin_fill()
t.pendown()
t.forward(300)
t.left(150)
t.forward(230)
t.right(150)
t.forward(150)
t.left(150)
t.forward(290)
t.left(120)
t.forward(260)
t.end_fill()

t.penup()
t.setheading(0)
t.goto(360,10)
t.color("#DC143C")
t.fillcolor("#DC143C")
t.begin_fill()
t.pendown()
t.forward(255)
t.left(150)
t.forward(225)
t.right(150)
t.forward(145)
t.left(150)
t.forward(238)
t.left(120)
t.forward(230)
t.end_fill()

# Moon
t.penup()
t.setheading(0)
t.goto(410,135)
draw_circle(30,"white")
t.goto(410,145)
draw_circle(30,"#DC143C")
#sun over moon
t.penup()
t.setheading(0)
t.goto(395,158)
t.color("white")
t.fillcolor("white")
t.begin_fill()
t.pendown()
for i in range(11):
    t.forward(30)
    t.right(131) 
t.end_fill()
#sun
t.penup()
t.setheading(0)
t.goto(380,70)
t.color("white")
t.fillcolor("white")
t.begin_fill()
t.pendown()
for i in range(11):
    t.forward(60)
    t.right(131) 
t.end_fill()
t.penup()
##### Draw flag end ####

### Music Bar Starts #####
t.hideturtle()
equalizer_bar1=turtle.Pen()
equalizer_bar1.hideturtle()
equalizer_bar1.shape("square")
equalizer_bar1.pensize(20)
equalizer_bar1.penup()
equalizer_bar1.goto(100,-300)
equalizer_bar1.setheading(0)
equalizer_bar1.color("white")
equalizer_bar1.pendown()
equalizer_bar1.speed(10)
equalizer_bar1.left(90)
equalizer_bar1.forward(5)

equalizer_bar2=turtle.Pen()
equalizer_bar2.hideturtle()
equalizer_bar2.pensize(20)
equalizer_bar2.penup()
equalizer_bar2.goto(120,-300)
equalizer_bar2.setheading(0)
equalizer_bar2.color("white")
equalizer_bar2.pendown()
equalizer_bar2.speed(4)
equalizer_bar2.left(90)
equalizer_bar2.forward(5)

equalizer_bar3=turtle.Pen()
equalizer_bar3.hideturtle()
equalizer_bar3.pensize(20)
equalizer_bar3.penup()
equalizer_bar3.goto(140,-300)
equalizer_bar3.setheading(0)
equalizer_bar3.color("white")
equalizer_bar3.pendown()
equalizer_bar3.speed(8)
equalizer_bar3.left(90)
equalizer_bar3.forward(5)

equalizer_bar4=turtle.Pen()
equalizer_bar4.hideturtle()
equalizer_bar4.pensize(20)
equalizer_bar4.penup()
equalizer_bar4.goto(160,-300)
equalizer_bar4.setheading(0)
equalizer_bar4.color("white")
equalizer_bar4.pendown()
equalizer_bar4.speed(6)
equalizer_bar4.left(90)
equalizer_bar4.forward(5)

equalizer_bar5=turtle.Pen()
equalizer_bar5.hideturtle()
equalizer_bar5.pensize(20)
equalizer_bar5.penup()
equalizer_bar5.goto(180,-300)
equalizer_bar5.setheading(0)
equalizer_bar5.color("white")
equalizer_bar5.pendown()
equalizer_bar5.speed(9)
equalizer_bar5.left(90)
equalizer_bar5.forward(5)

equalizer_bar6=turtle.Pen()
equalizer_bar6.hideturtle()
equalizer_bar6.pensize(20)
equalizer_bar6.penup()
equalizer_bar6.goto(200,-300)
equalizer_bar6.setheading(0)
equalizer_bar6.color("white")
equalizer_bar6.pendown()
equalizer_bar6.speed(15)
equalizer_bar6.left(90)
equalizer_bar6.forward(5)

turtle.colormode(255) #defining color mode to RGB 255
for i in range(30):
    R1 = random.randint(0,255)
    G1 = random.randint(0,255)
    B1 = random.randint(0,255)
    rand_height1 = random.randint(10,200)
    equalizer_bar1.color(R1,G1,B1)
    equalizer_bar1.forward(rand_height1)
    equalizer_bar1.color(background_color)
    equalizer_bar1.backward(rand_height1)
    
    R2 = random.randint(0,255)
    G2 = random.randint(0,255)
    B2 = random.randint(0,255)
    rand_height2 = random.randint(10,200)
    equalizer_bar2.color(R2,G2,B2)
    equalizer_bar2.forward(rand_height2)
    equalizer_bar2.color(background_color)
    equalizer_bar2.backward(rand_height2)

    R3 = random.randint(0,255)
    G3 = random.randint(0,255)
    B3 = random.randint(0,255)
    rand_height3 = random.randint(10,200)
    equalizer_bar3.color(R3,G3,B3)
    equalizer_bar3.forward(rand_height3)
    equalizer_bar3.color(background_color)
    equalizer_bar3.backward(rand_height3)
    
    R4 = random.randint(0,255)
    G4 = random.randint(0,255)
    B4 = random.randint(0,255)
    rand_height4 = random.randint(10,200)
    equalizer_bar4.color(R4,G4,B4)
    equalizer_bar4.forward(rand_height4)
    equalizer_bar4.color(background_color)
    equalizer_bar4.backward(rand_height4)
    
    R5 = random.randint(0,255)
    G5 = random.randint(0,255)
    B5 = random.randint(0,255)
    rand_height5 = random.randint(10,200)
    equalizer_bar5.color(R5,G5,B5)
    equalizer_bar5.forward(rand_height5)
    equalizer_bar5.color(background_color)
    equalizer_bar5.backward(rand_height5)
    
    R6 = random.randint(0,255)
    G6 = random.randint(0,255)
    B6 = random.randint(0,255)
    rand_height6 = random.randint(10,200)
    equalizer_bar6.color(R6,G6,B6)
    equalizer_bar6.forward(rand_height6)
    equalizer_bar6.color(background_color)
    equalizer_bar6.backward(rand_height6)
    
equalizer_bar1.penup()
equalizer_bar2.penup()
equalizer_bar3.penup()
equalizer_bar4.penup()
equalizer_bar5.penup()
equalizer_bar6.penup()
### Music Bar Ends ###

delay = input("Press enter to finish.")
